### ISSUE TITLE
"Copy Notes" appears to copy date page was loaded rather than date it's clicked

### ISSUE THREAD

**Issue by GlennHS** [stuartajd/scrum#2]
Clicking "Copy Notes" adds the notes to clipboard but the date is wrong. It uses the date the webpage was launched rather than the date the button's clicked

Tested on Chrome, latest version, Windows 10

**Comment by stuartajd** [comment]
Updated this - https://github.com/stuartajd/scrum/commit/cc5f9e696061de5ed1eaf02a1e44fd7c5e3e93e8

Thanks for the issue 😺
