### ISSUE TITLE
"Blocked: No" still has "Blocked Reason" shown

### ISSUE THREAD

**Issue by GlennHS** [stuartajd/scrum#8]
When setting a task's blocked status to "No" the "Blocked Reason" field is still shown in the copied notes

![image](https://user-images.githubusercontent.com/12845762/159883509-3aa3a3e3-66e7-4fc9-a9bb-9ebf5bc6ccbd.png)

**Comment by stuartajd** [comment]
Should be fixed now! 🕺🏻  Thanks 💯
